---
- name: Load variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Configure SSH server
  lineinfile: >
    dest="{{ sshd_config }}"
    regexp="(?i)^\s*{{ item.key }}"
    line="{{ item.key }} {{ item.value }}"
    insertafter="(?i)^\s*#?\s*{{ item.key }}\s+\S+"
    validate="sshd -tf %s"
  with_dict: "{{ sshd_settings }}"
  notify: Reload SSH server
